 
#!/usr/bin/env python3
"""
gnome-appstream-desktop-localize.py

Scan installed GNOME .desktop files, find their AppStream metadata,
copy the original desktop files to ~/.local/share/applications/,
and add localized Name[...] entries from AppStream.

Designed for KDE Plasma / Plasma 6, but also works with Plasma 5.

No system files are modified.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Optional, Tuple


XML_LANG = "{http://www.w3.org/XML/1998/namespace}lang"
MARKER = "# Generated by gnome-appstream-desktop-localize.py"


# ------------------------------------------------------------
# XDG / Flatpak paths
# ------------------------------------------------------------

def xdg_data_dirs() -> List[Path]:
    data_home = Path(
        os.environ.get(
            "XDG_DATA_HOME",
            str(Path.home() / ".local/share")
        )
    ).expanduser()

    raw = os.environ.get(
        "XDG_DATA_DIRS",
        "/usr/local/share:/usr/share"
    )

    dirs = [data_home]
    dirs.extend(
        Path(p).expanduser()
        for p in raw.split(":")
        if p
    )

    return dirs


def desktop_dirs() -> List[Path]:
    """
    Search order:
      1. user Flatpak exports
      2. system Flatpak exports
      3. normal XDG application directories
    """

    candidates = [
        Path.home()
        / ".local/share/flatpak/exports/share/applications",

        Path("/var/lib/flatpak/exports/share/applications"),
    ]

    candidates += [
        d / "applications"
        for d in xdg_data_dirs()
    ]

    result = []
    seen = set()

    for directory in candidates:
        directory = directory.expanduser()

        if not directory.is_dir():
            continue

        key = str(directory)

        if key in seen:
            continue

        seen.add(key)
        result.append(directory)

    return result


def metainfo_dirs() -> List[Path]:
    """
    Search AppStream metadata in normal XDG locations and Flatpak exports.
    """

    candidates = [
        Path.home()
        / ".local/share/flatpak/exports/share/metainfo",

        Path("/var/lib/flatpak/exports/share/metainfo"),

        Path.home() / ".local/share/metainfo",
        Path.home() / ".local/share/appdata",
    ]

    for directory in xdg_data_dirs():
        candidates.extend([
            directory / "metainfo",
            directory / "appdata",
        ])

    result = []
    seen = set()

    for directory in candidates:
        directory = directory.expanduser()

        if not directory.is_dir():
            continue

        key = str(directory)

        if key in seen:
            continue

        seen.add(key)
        result.append(directory)

    return result


# ------------------------------------------------------------
# Desktop file handling
# ------------------------------------------------------------

def desktop_id_for_path(path: Path, root: Path) -> str:
    """
    Convert relative desktop path to Desktop File ID.

    Example:
      foo/bar.desktop -> foo-bar.desktop
    """

    relative = path.relative_to(root)

    return str(relative).replace(os.sep, "-")


def read_desktop_type(path: Path) -> Optional[str]:
    try:
        text = path.read_text(
            encoding="utf-8-sig",
            errors="replace"
        )
    except OSError:
        return None

    in_desktop_entry = False

    for raw_line in text.splitlines():
        line = raw_line.strip()

        if line == "[Desktop Entry]":
            in_desktop_entry = True
            continue

        if in_desktop_entry and line.startswith("["):
            break

        if in_desktop_entry and line.startswith("Type="):
            return line.split("=", 1)[1].strip()

    return None


def collect_desktops() -> Dict[str, Path]:
    """
    Collect Application desktop files.

    The first matching Desktop File ID wins, following the usual
    XDG precedence model.
    """

    result: Dict[str, Path] = {}

    for root in desktop_dirs():

        for path in root.rglob("*.desktop"):

            if read_desktop_type(path) != "Application":
                continue

            try:
                desktop_id = desktop_id_for_path(path, root)
            except (ValueError, OSError):
                continue

            result.setdefault(desktop_id, path)

    return result


# ------------------------------------------------------------
# Locale conversion
# ------------------------------------------------------------

def appstream_locale_to_desktop_locale(
    tag: str
) -> Optional[str]:
    """
    Convert common AppStream / BCP47 language tags into
    Desktop Entry POSIX-style locale tags.

    Examples:

      zh-TW  -> zh_TW
      zh_CN  -> zh_CN
      pt-BR  -> pt_BR
      ja     -> ja
    """

    if not tag:
        return None

    tag = tag.strip()

    if tag in {"C", "POSIX"}:
        return None

    modifier = ""

    if "@" in tag:
        tag, mod = tag.split("@", 1)
        modifier = "@" + mod

    parts = [
        part
        for part in re.split(r"[-_]", tag)
        if part
    ]

    if not parts:
        return None

    # Ignore BCP47 extension/private-use subtags that cannot
    # be meaningfully represented as a normal Desktop Entry locale.
    cleaned = []

    for index, part in enumerate(parts):

        if index > 0 and len(part) == 1:
            break

        cleaned.append(part)

    if not cleaned:
        return None

    return "_".join(cleaned) + modifier


# ------------------------------------------------------------
# AppStream parsing
# ------------------------------------------------------------

def appstream_component_is_gnome(
    component: ET.Element,
    desktop_id: str
) -> bool:

    # Useful fallback for GNOME applications whose metadata
    # does not explicitly contain <project_group>GNOME</project_group>.
    if desktop_id.startswith("org.gnome."):
        return True

    project_group = component.find("./project_group")

    if project_group is not None:
        value = (project_group.text or "").strip()

        if value.lower() == "gnome":
            return True

    return False


def parse_metainfo(
    path: Path
) -> List[
    Tuple[
        bool,
        List[str],
        Dict[str, str]
    ]
]:

    try:
        root = ET.parse(path).getroot()
    except (ET.ParseError, OSError):
        return []

    if root.tag == "component":
        components = [root]
    else:
        components = root.findall(".//component")

    results = []

    for component in components:

        component_type = component.get("type")

        if component_type not in (
            None,
            "desktop",
            "desktop-application",
        ):
            continue

        desktop_ids = []

        # Modern AppStream association.
        for launchable in component.findall("./launchable"):

            if launchable.get("type") != "desktop-id":
                continue

            if not launchable.text:
                continue

            desktop_id = launchable.text.strip()

            if "/" in desktop_id:
                desktop_id = desktop_id.replace("/", "-")

            if not desktop_id.endswith(".desktop"):
                desktop_id += ".desktop"

            desktop_ids.append(desktop_id)

        # Compatibility with older AppStream metadata.
        component_id = component.findtext(
            "./id",
            default=""
        ).strip()

        if component_id.endswith(".desktop"):
            desktop_ids.append(component_id)

        desktop_ids = list(dict.fromkeys(desktop_ids))

        if not desktop_ids:
            continue

        names: Dict[str, str] = {}

        for name_node in component.findall("./name"):

            text = "".join(
                name_node.itertext()
            ).strip()

            if not text:
                continue

            raw_locale = name_node.get(
                XML_LANG,
                ""
            )

            locale = appstream_locale_to_desktop_locale(
                raw_locale
            )

            if locale:
                names.setdefault(locale, text)
            else:
                # Default "C" name. It is not installed as Name[...].
                names.setdefault("", text)

        if not names:
            continue

        is_gnome = any(
            appstream_component_is_gnome(
                component,
                desktop_id
            )
            for desktop_id in desktop_ids
        )

        results.append(
            (
                is_gnome,
                desktop_ids,
                names,
            )
        )

    return results


def build_appstream_index():
    """
    Return:

      desktop-id ->
          (
              is_gnome,
              localized_names,
              metadata_file
          )
    """

    index = {}

    for directory in metainfo_dirs():

        for xml_file in directory.rglob("*.xml"):

            for is_gnome, desktop_ids, names in parse_metainfo(
                xml_file
            ):

                for desktop_id in desktop_ids:

                    if desktop_id not in index:
                        index[desktop_id] = (
                            is_gnome,
                            dict(names),
                            xml_file,
                        )
                        continue

                    old_gnome, old_names, old_file = index[
                        desktop_id
                    ]

                    # Prefer a GNOME component over a non-GNOME
                    # component using the same desktop ID.
                    if is_gnome and not old_gnome:
                        index[desktop_id] = (
                            True,
                            dict(names),
                            xml_file,
                        )
                        continue

                    if is_gnome == old_gnome:

                        merged = dict(old_names)

                        for locale, value in names.items():
                            merged.setdefault(
                                locale,
                                value
                            )

                        index[desktop_id] = (
                            old_gnome,
                            merged,
                            old_file,
                        )

    return index


# ------------------------------------------------------------
# Desktop Entry localization
# ------------------------------------------------------------

def existing_name_locales(
    lines: List[str]
) -> set:

    result = set()

    in_desktop_entry = False

    for line in lines:

        stripped = line.strip()

        if stripped == "[Desktop Entry]":
            in_desktop_entry = True
            continue

        if in_desktop_entry and stripped.startswith("["):
            break

        if not in_desktop_entry:
            continue

        match = re.match(
            r"^Name\[([^\]]+)\]\s*=",
            stripped
        )

        if match:
            result.add(match.group(1))

    return result


def escape_desktop_value(value: str) -> str:
    """
    Minimal escaping needed for a Desktop Entry string.
    """

    return (
        value
        .replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def insert_localized_names(
    text: str,
    names: Dict[str, str],
) -> Tuple[str, List[str]]:

    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    lines = text.splitlines()

    already_present = existing_name_locales(lines)

    wanted = []

    for locale, value in names.items():

        if not locale:
            continue

        if locale in already_present:
            continue

        wanted.append(
            (locale, value)
        )

    if not wanted:
        return text, []

    wanted.sort(
        key=lambda item: item[0].lower()
    )

    localized_lines = [
        f"Name[{locale}]={escape_desktop_value(value)}"
        for locale, value in wanted
    ]

    for index, line in enumerate(lines):

        if line.strip().startswith("Name="):

            result = (
                lines[:index + 1]
                + localized_lines
                + lines[index + 1:]
            )

            return (
                "\n".join(result) + "\n",
                [locale for locale, _ in wanted],
            )

    # Name is required for Application desktop entries, but
    # do not fabricate anything if the file is malformed.
    return text, []


# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

def main() -> int:

    parser = argparse.ArgumentParser(
        description=(
            "Generate localized GNOME desktop-entry overrides "
            "for KDE Plasma using AppStream metadata."
        )
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="show changes without writing files",
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "replace existing user overrides; "
            "normally non-generated files are left untouched"
        ),
    )

    parser.add_argument(
        "--no-refresh",
        action="store_true",
        help="do not run kbuildsycoca6/kbuildsycoca5",
    )

    parser.add_argument(
        "--all-matched",
        action="store_true",
        help=(
            "process every desktop entry with AppStream metadata, "
            "not only GNOME applications"
        ),
    )

    parser.add_argument(
        "--locale",
        action="append",
        help=(
            "only generate the specified locale; "
            "can be supplied multiple times, e.g. "
            "--locale zh_TW --locale ja"
        ),
    )

    args = parser.parse_args()

    desktops = collect_desktops()
    appstream = build_appstream_index()

    data_home = Path(
        os.environ.get(
            "XDG_DATA_HOME",
            str(Path.home() / ".local/share")
        )
    ).expanduser()

    output_dir = data_home / "applications"

    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    wanted_locales = None

    if args.locale:

        wanted_locales = set()

        for raw_locale in args.locale:

            locale = appstream_locale_to_desktop_locale(
                raw_locale
            )

            if locale:
                wanted_locales.add(locale)

    changed = 0
    skipped = 0

    for desktop_id, source_file in sorted(
        desktops.items()
    ):

        appstream_entry = appstream.get(
            desktop_id
        )

        if not appstream_entry:
            continue

        is_gnome, names, metadata_file = (
            appstream_entry
        )

        if not args.all_matched and not is_gnome:
            continue

        if wanted_locales is not None:

            names = {
                locale: value
                for locale, value in names.items()
                if locale in wanted_locales
            }

        if not names:
            continue

        destination = output_dir / desktop_id

        try:
            original_text = source_file.read_text(
                encoding="utf-8-sig",
                errors="replace",
            )
        except OSError as error:

            print(
                f"WARN: cannot read {source_file}: {error}",
                file=sys.stderr,
            )

            continue

        # Don't destroy an existing hand-written override unless
        # --force is explicitly used.
        if destination.exists() and not args.force:

            try:
                old_text = destination.read_text(
                    encoding="utf-8",
                    errors="replace",
                )
            except OSError:
                old_text = ""

            if MARKER not in old_text:

                skipped += 1

                print(
                    f"skip existing user override: {destination}"
                )

                continue

        generated, locales = insert_localized_names(
            original_text,
            names,
        )

        if not locales:
            continue

        generated = (
            MARKER
            + "\n"
            + generated
        )

        if args.dry_run:

            print(
                f"{desktop_id}: "
                f"{', '.join(locales)} "
                f"<- {metadata_file}"
            )

            changed += 1
            continue

        temporary = destination.with_suffix(
            ".desktop.tmp"
        )

        try:

            temporary.write_text(
                generated,
                encoding="utf-8",
            )

            os.replace(
                temporary,
                destination,
            )

        except OSError as error:

            print(
                f"WARN: cannot write {destination}: {error}",
                file=sys.stderr,
            )

            try:
                temporary.unlink(
                    missing_ok=True
                )
            except OSError:
                pass

            continue

        print(
            f"generated {destination} "
            f"({', '.join(locales)})"
        )

        changed += 1

    # Rebuild KDE's application service cache.
    if (
        changed
        and not args.dry_run
        and not args.no_refresh
    ):

        for command in (
            "kbuildsycoca6",
            "kbuildsycoca5",
        ):

            executable = shutil.which(
                command
            )

            if not executable:
                continue

            subprocess.run(
                [executable],
                check=False,
            )

            break

    print()
    print(
        f"Done: {changed} generated/updated, "
        f"{skipped} existing user overrides skipped."
    )

    print(
        f"Desktop entries scanned: {len(desktops)}"
    )

    print(
        f"AppStream desktop mappings: "
        f"{len(appstream)}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )